- tests/testthat/test-odin-dust.R
Minor update to a test now that dust does not filter the data by default
> Fix tests to cope with changes in dust 0.1.0

- .travis.yml
- DESCRIPTION
- R/generate_dust.R
- R/odin_dust.R
- R/package.R
- inst/support.hpp
- man/odin_dust_package.Rd
- tests/testthat/examples/pkg/DESCRIPTION
- tests/testthat/examples/pkg/NAMESPACE
- tests/testthat/helper-odin-dust.R
- tests/testthat/test-odin-dust.R
- tests/testthat/test-user.R
- tests/testthat/wrapper-user.cpp
This PR should be considered in conjunction with the corresponding PR in dust (https://github.com/mrc-ide/dust/pull/39).
**Unpin the dust version before merge**
Fixes #12
> i12: replace Rcpp with cpp11

- DESCRIPTION
- R/generate_dust.R
- R/utils.R
> Same deparse strategy as odin

- .github/workflows/make-release.yaml
- DESCRIPTION
Creates a release to github on merge
> Release on merge

- DESCRIPTION
- NEWS.md
- R/common.R
- tests/testthat/test-sexp.R
> Support for as.integer

- DESCRIPTION
- NEWS.md
- vignettes/sir_models.Rmd
- vignettes/sirage.R
Corrects the scaling of beta in the age-structured model example in the vignette
> Update sirage vignette with correct scaling

- DESCRIPTION
- R/generate_dust.R
- vignettes/sir_models.Rmd
Minor updates here.
Merge https://github.com/mrc-ide/dust/pull/131 first and unpin Remotes
> Updates to work with dust 0.6.0

- DESCRIPTION
- R/generate_dust.R
Pleasingly minor changes as we were basically targetting this interface already by convention and this just formalises it.
Depends on https://github.com/mrc-ide/dust/pull/144 (update branch pointer before merge)
Fixes #59
> Update to work with dust 0.7.0

- DESCRIPTION
- R/generate_dust.R
- R/generate_dust_sexp.R
- R/utils.R
- tests/testthat/test-gpu.R
- tests/testthat/test-sexp.R
Generates code compatible with https://github.com/mrc-ide/dust/pull/168
> Start generating new shared code

- DESCRIPTION
- NEWS.md
- R/generate_dust.R
- tests/testthat/examples/compare.cpp
- tests/testthat/examples/compare_simple.cpp
- tests/testthat/test-compare.R
Will add tests shortly though there's no actual logic in here
> Add real_t typedef into dust_data

- DESCRIPTION
- NEWS.md
- R/common.R
- tests/testthat/test-sexp.R
Requires https://github.com/mrc-ide/odin/pull/221
Fixes #79
> Add support for as.numeric

- DESCRIPTION
- R/generate_dust.R
- tests/testthat/test-gpu.R
Minor tweaks required after merging https://github.com/mrc-ide/dust/pull/302
> Update to work with dust 0.11.0

- .gitignore
- DESCRIPTION
- R/generate_dust.R
- R/generate_dust_equation.R
- R/odin_dust.R
- tests/testthat/examples/age.R
- tests/testthat/test-odin-dust.R
Adds `mode` as a compilation target
> mrc-3272 compile ODE models to mode 

- DESCRIPTION
- R/generate_dust.R
- R/generate_dust_equation.R
- tests/testthat/test-odin-dust.R
Follows from #102, and requires https://github.com/mrc-ide/mode/pull/24 and https://github.com/mrc-ide/odin/pull/261 to be merged first
Support for compilation of simple mixed models, probably enough for us to implement the malaria model completely
> Compile mixed models

- R/generate_dust.R
- R/utils.R
See comments on review of #105
> Suggestions for review

- DESCRIPTION
would you also increment the version of this package itself when changing a dependency like this? :thinking:
> increment mode version

- DESCRIPTION
- R/common.R
- R/generate_dust.R
- README.md
- tests/testthat/test-odin-dust.R
- vignettes/porting.Rmd
~This depends on https://github.com/mrc-ide/dust/pull/370, which is still in progress but largely working.~
Implementation is pretty trivial, but I also ruled out using rmhyper and rmultinom as the previous error message was incomprehensible (reported by @cwhittaker1000)
> Support for hypergeometric distribution in models

- DESCRIPTION
- NEWS.md
- R/common.R
- tests/testthat/test-odin-dust.R
- vignettes/porting.Rmd
Pulls in the new support added in dust
> Add support for rgamma and rnbinom

- DESCRIPTION
- tests/testthat/test-compare.R
- tests/testthat/test-gpu.R
- tests/testthat/test-odin-dust.R
- tests/testthat/test-package.R
- vignettes/porting.Rmd
- vignettes/sir_models.Rmd
No actual changes to implementation, just need to patch up the docs and tests a bit
> Update to use "time" not "step" in dust 0.12.x

- DESCRIPTION
- R/generate_dust.R
- R/odin_dust.R
- R/utils.R
Mostly walking back some of the changes introduced with mode in preparation for merging that back in
> Fixes for recent mode/dust

- DESCRIPTION
- R/generate_dust.R
- tests/testthat/test-odin-dust.R
Depends on https://github.com/mrc-ide/dust/pull/400; update branch pin before merge
> Allow use of stochastic functions in initial conditions

- DESCRIPTION
- R/odin_dust.R
- man/odin_dust_options.Rd
- tests/testthat/test-odin-dust.R
Requires https://github.com/mrc-ide/dust/pull/409, otherwise fairly trivial
Fixes #77
> Pass through compilation options to dust

- DESCRIPTION
- R/generate_dust.R
- R/generate_dust_equation.R
- R/generate_dust_sexp.R
- tests/testthat/test-compare.R
- tests/testthat/test-gpu.R
A proof of concept automatic compiled compare function using the new odin support for describing compare and data.
~Note that this does not currently work with ode models it seems~
~Uses https://github.com/mrc-ide/odin/pull/294~
> Proof of concept new compare function
