.travis.yml
DESCRIPTION
R/generate_dust.R
R/generate_dust_equation.R
R/generate_dust_sexp.R
R/odin_dust.R
R/utils.R
inst/support.hpp
man/odin_dust.Rd
tests/testthat/test-odin-dust.R
tests/testthat/test-utils.R

This PR starts the process of making odin.dust capable of generating models with different real and integer types. The type is pulled through from the interface and added to the generated code - that part is pretty straightforward.
There's some harder work to be done in the user handling, and as such user-vectors are not supported in float-using models (see #6 for details)
**NOTE**: Update branch pin in .travis.yml before merge, after the dust PR is merged
Requires https://github.com/mrc-ide/dust/pull/28
Fixes #4

i4: Allow specification of numerical types

---

.travis.yml
DESCRIPTION
R/generate_dust.R
R/odin_dust.R
R/utils.R
tests/testthat/test-odin-dust.R

This PR uses the support in https://github.com/mrc-ide/dust/pull/30 to return variable ordering information back from dust. This is needed because odin is allowed to reorder variables as it wants (i.e. the way that the state vector is packed - roughly it will be scalars then vectors, I think each in topological order given the graph).
We provide two methods here:
* `$info()` comes directly from the support in dust and here returns something like: `list(x = 1, y = 10, z = c(3, 5))` which would mean `x` is a scalar `y` is a vector of length 10 and `z` is a matrix if 3 rows and 5 columns
* `$index()` returns the *index* to the state vector (given that) so `list(x = 1, y = 2:11, z = 12:56)`
With this, in sircovid we can then get the deaths index out for the compare function, but we still need …

i7 - return variable order

---

DESCRIPTION
tests/testthat/test-odin-dust.R

Minor updates to the test now that the dust RNG is exported with a proper API

Update to use new dust rng interface

---

DESCRIPTION
R/generate_dust_sexp.R
R/utils.R
inst/support.hpp
tests/testthat/examples/sum2.R
tests/testthat/test-odin-dust.R
tests/testthat/test-sexp.R

The sum implementation was broken because we passed a different type for things stored as variables (which come out as `real_t *`) and things stored as intermediates (which come out as `std::vector<real_t>`), creating a compiler error.
This PR changes `sum` so that we use the lowest common denominator of the pointer, even though that's a bit ugly. Using iterators would be more general but somewhat harder and may not work nicely on the GPU.
Fixes #15

i15: fix sum for variables

---

R/odin_dust.R
man/odin_dust.Rd
tests/testthat/test-odin-dust.R

This PR just passes the `workdir` argument through to dust, which allows for persistent models, and easier inspection of the code.
Fixes #16

i16: Pass workdir through to dust

---

.travis.yml
DESCRIPTION
R/generate_dust.R
R/generate_dust_sexp.R
R/odin_dust.R
R/utils.R
inst/support.hpp
man/odin_dust.Rd
tests/testthat/test-odin-dust.R
tests/testthat/test-sexp.R

Uses rng state rather than an RNG object. Surprisingly little impact on the generated code, which is nice.
Due to some version leapfrogging this also includes now #23:
This PR generates code that can use dust 0.4.0's GPU capability
The same code will run without problem with dust >= 0.3.0
Fixes #22
Fixes #20

i20: update to dust 0.4.1

---

DESCRIPTION
R/generate_dust.R
R/odin_dust.R
R/package.R
R/utils.R
inst/support.hpp
tests/testthat/test-odin-dust.R
tests/testthat/test-package.R

This PR updates the generated interface to better suit mcstate: the index variables are always computed, and sit alongside info. I've added a simplified version of transform_variables on top of this, which will help too for complicated models.
~Depends on #21 (as it builds on it)~
Fixes #24

i24: Set index within the result of info()

---

DESCRIPTION
NEWS.md
inst/support.hpp
tests/testthat/test-odin-dust.R

This was not that bad in the end; one extra function (`user_get_array_value`) to avoid a partial template specification. We could possibly implement this by a specialisation on `cpp11::as_cpp` but one extra small copy feels ok here.
Lots of details changed in `user_check_value` but the end result is the same.
Fixes #6

Basic implementation of float vectors

---

DESCRIPTION
NEWS.md
R/generate_dust.R
R/generate_dust_sexp.R
inst/support.hpp
tests/testthat/test-sexp.R

Support for sharing constant memory between particles. Creates a shared_ptr to a const struct that all particles can read from; see https://github.com/mrc-ide/dust/pull/124 for the approach
Merge after ~#44 as this PR builds on it, and after~ https://github.com/mrc-ide/odin/pull/215 is merged (update the `DESCRIPTION` to remove the branch pin)
This is somewhat tedious to benchmark, but at least for sircovid this makes no difference at all with identical timings. I'd expect memory usage to be slightly lower, but because we don't go through R's allocator `bench` is not reporting sensible numbers.
Still, hopefully this will prove useful for the GPU work, at least as a proof-of-concept
Fixes #45

Support for sharing constant memory between particles

---

DESCRIPTION
NEWS.md
R/common.R
tests/testthat/test-odin-dust.R
tests/testthat/test-sexp.R

Implements `a %% b` by translating to `std::fmod(a, b)`
We might want to extend this to be R's fancy modulo which differs for negative values but that's not needed right now and runs into some issues with needing to change the order of includes
Fixes #52

Basic modulo

---

DESCRIPTION
NEWS.md
R/generate_dust.R
R/odin_dust.R
tests/testthat/examples/compare.cpp
tests/testthat/examples/compare_simple.cpp
tests/testthat/test-compare.R

Requires and builds on https://github.com/mrc-ide/dust/pull/132 and https://github.com/mrc-ide/odin/pull/216
Basically undocumented and probably should remain so until we manage to get this working with sircovid, at which point we'll have to write a series of vignettes. However, the example in the tests is hopefully fairly self-explanatory.
Fixes #51

Create compiled comparison functions

---

DESCRIPTION
R/generate_dust.R
R/odin_dust.R
R/package.R
R/utils.R
tests/testthat/examples/compare_simple.cpp
tests/testthat/test-compare.R
tests/testthat/test-odin-dust.R
tests/testthat/test-package.R

In trying to wire this up with sircovid it turned out I'd failed to test (or implement correctly) the package interface to this.
This has become a bit of an omnibus PR with a number of bugs and unpleasantnesses fixed:
* generated code no longer includes whitespace (in C++), with test
* moved away from glue for the odin substitution because it's escape behaviour mangled code (`))` became `)` because it was an exactly-doubled closing marker)
* generating the data struct constructor was broken if it contained more than one element
* odin_dust() did not work with compare function when the source was in a subdirectory
Fixes #55

Correct and test compiled comparison in package

---

DESCRIPTION
vignettes/sir_models.Rmd

Fixed typo from `-` to `+` in `R_{t+1}` of `sir_models.Rmd`

Fix typo in sir_models.Rmd

---

DESCRIPTION
NEWS.md
R/generate_dust.R
R/generate_dust_equation.R
R/generate_dust_sexp.R
R/odin_dust.R
R/utils.R
inst/support.hpp
man/odin_dust.Rd
tests/testthat/test-gpu.R
tests/testthat/test-odin-dust.R
tests/testthat/test-sexp.R

Uses the support introduced in https://github.com/mrc-ide/dust/pull/164 which is incomplete. This PR lets us generate fairly complicated update functions (theoretically that of sircovid?) which will make further development of the gpu code much easier.
Changes are relatively minor here:
* light rewriting of the equations involved in the update as we've moved a few things in internal
* some changes to the sum functions - note explicit specification of the return type now as the container type and value type are now unrelated
* additional argument to the main odin_dust function to turn on this support
It's not enabled by default, and not enabled at all in packages; that will give us freedom to tinker with the toolchain in dust

Generate code for models on gpu

---

DESCRIPTION
R/generate_dust.R
R/generate_dust_equation.R
tests/testthat/test-odin-dust.R

This was never actually added to odin.dust it seems, but dust never supported it. However, some vestiges had made it across in the prototype
Fixes #62

Formally remove output

---

DESCRIPTION
Makefile
NEWS.md
R/generate_dust.R
R/generate_dust_equation.R
R/generate_dust_sexp.R
R/odin_dust.R
R/utils.R
tests/testthat/test-sexp.R

This PR totally rewrites the gpu code so that rather than generating code like the CPU version where we unpack everything then run each equation in turn, we unpack locally to each expression. The hope here is that reduces the register pressure (and indeed with sircovid it does)
Fixes #75

Create GPU code with scoped expressions to reduce register pressure

---

DESCRIPTION
R/generate_dust.R
tests/testthat/test-compare.R
tests/testthat/test-gpu.R

Support for device compiled compare functions
This needs merging in concert with https://github.com/mrc-ide/sircovid/pull/297 and https://github.com/mrc-ide/dust/pull/224

Update to work with dust 0.9.0

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
R/generate_dust.R
tests/testthat/test-gpu.R

This fixes a bug seen by @RaphaelS1 in https://github.com/mrc-ide/sircovid/pull/306 where code generation failed if two (or more) shared integer vectors were present, because offset generation failed. A little fiddly but the original solution was very close

Allow two shared integer vectors

---

DESCRIPTION
tests/testthat/test-gpu.R

Affects only the tests, which replace device_id with device_config
Can be merged after https://github.com/mrc-ide/dust/pull/246, all
generated code is still ok

Minor updates to work with new dust

---

DESCRIPTION
NEWS.md
R/generate_dust_sexp.R
tests/testthat/test-sexp.R

This PR fixes a stack overflow seen by Ed when generating gpu code for sircovid as this includes a very large sum (hundreds of terms). That causes odin's recursive rewrite to fail. Here, we unfold the tree `(+ (+ (+ a b) c) d)` to `(+ a b c d)` which prevents this

Avoid stack overflow when generating large sums

---

DESCRIPTION
R/generate_dust_equation.R
tests/testthat/helper-odin-dust.R
tests/testthat/test-user.R

As found by @annecori, we wrote code that performed poorly on an ARM Mac.
The testing is not ideal, but should at least prevent regressions. There's no obvious way of triggering this without running on an M1 which is not really possible in a CI environment.  Fix confirmed on Anne's machine.

Use correct NA value for user handling

---

DESCRIPTION
vignettes/porting.Rmd

This PR adds a new vignette which tries to explain some of the differences between vanilla odin models and those in odin.dust, based on things I have explained over Teams. No doubt it will need expanding over time

Add porting guide

---

DESCRIPTION
R/generate_dust.R
tests/testthat/test-odin-dust.R

This is basically impossible to test, because compiler warnings are really unportable.
At the moment though, this model produces a set of warnings, if you have things turned up noisy enough:
```r
odin.dust::odin_dust({
initial(x) <- step + 1
update(x) <- x
})
```
```
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/home/rich/lib/R/library/cpp11/include' -g -Wall -Wextra -pedantic -Wmaybe-uninitialized -Wno-unused-parameter -Wno-cast-function-type -Wno-missing-field-initializers -O2  -I/home/rich/lib/R/library/dust/include -DHAVE_INLINE -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-BNt0N4/r-base-4.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c dust.cpp -o dust.o
dust.cpp: In function ‘dust::pars_type<T> …
```

Avoid compiler warnings with initial time varying

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml
DESCRIPTION
R/generate_dust.R
R/odin_dust.R
man/odin_dust.Rd
tests/testthat/test-odin-dust.R

This PR uses additional comments/attributes to control the C++ standard and additional packages used by dust (see https://github.com/mrc-ide/dust/pull/380 and https://github.com/mrc-ide/dust/pull/381).
~Contains commits from #120; until that is megrged, see https://github.com/mrc-ide/odin.dust/compare/mrc-3832...mrc-3829 for the diff~

Allow pulling in additional C++ dependencies

---

DESCRIPTION
NEWS.md
R/generate_dust.R
R/utils.R
tests/testthat/test-odin-dust.R

Requires https://github.com/mrc-ide/odin/pull/282 - update the branch pin before merge.
Fairly straightforward implementation here following the C one in odin, with one small wrinkle: we can't use `Rprintf` from multithreaded code! To get around this we can detect if we're running in parallel with `omp_in_parallel()` (this is true if we're in a block with more than one active thread), and then only evaluate _that_ function if OpenMP is available!

Add support for print() debugging

---

DESCRIPTION
R/generate_dust.R
tests/testthat/test-odin-dust.R

This PR fixes the code generation error spotted in #126, where the ODE interface was using `size_t` where it should have used `real_type` sometimes. Not too bad I think

Make sure we behave properly with noninteger time

---

DESCRIPTION
vignettes/porting.Rmd

The example needs to account for having to renormalise probabilities (over the remaining possible outcomes) in the nested binomial draws

Fix multinomial example in porting vignette

---

.lintr
DESCRIPTION
R/generate_dust.R
R/generate_dust_equation.R
R/utils.R
tests/testthat/test-interpolation.R
vignettes/porting.Rmd

Uses https://github.com/mrc-ide/dust/pull/415 so merge that first and update the branch pin.
This PR allows for basic interpolation, subject to some conditions:
* ~only piecewise constant and linear is supported~
* the interpolated y must be a scalar (i.e. no multivariable targets supported yet)
* does not work in discrete time models

Support for interpolation

---

DESCRIPTION
inst/support.hpp

Speculative fix for the issue Keith raised - 
See https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-5482/odin.dust-Rferror-type-warning 
or teams programming chat...

Cast size_t to uint for Rf_error
